USE aiqbal$default;

CREATE TABLE USERS(
	USER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
    USER_ADMIN TINYINT,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	USERNAME VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD_HASH VARCHAR(255) NOT NULL,
    SHORTEST_TIME TIME NOT NULL,
    LOWEST_NUMBER_OF_MISTAKES INT NOT NULL DEFAULT -1
);